#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

$pimple = new Pimple\Container();
$pimple->register(new \ServiceProvider\ApplicationProvider());
$pimple->register(new \ServiceProvider\ConsoleProvider());

$container = new \Pimple\Psr11\Container($pimple);

$application = $container->get(Application::class);

$application->run();
